package ni.edu.uni.programacion.views.panels;

import javax.swing.*;

/**
 *
 * @author Axel Moreno
 */
public class PnlTextEditor extends javax.swing.JPanel 
{

    /**
     * Creates new form PnlTextEditor
     */
    public PnlTextEditor() 
    {
        initComponents();
    }

    public JLabel getLblLetters()
    {
        return lblLetters;
    }

    public JLabel getLblLines() 
    {
        return lblLines;
    }

    public JLabel getLblWords()
    {
        return lblWords;
    }

    public JTextPane getTextPaneEditor()
    {
	return TextPaneEditor;
    }
    
    public void setTextPaneEditor(JTextPane TextPaneEditor)
    {
	this.TextPaneEditor = TextPaneEditor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLines = new javax.swing.JLabel();
        lblLetters = new javax.swing.JLabel();
        lblWords = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPaneEditor = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblLines.setForeground(new java.awt.Color(51, 51, 255));
        lblLines.setText("Lines:");
        jPanel1.add(lblLines);

        lblLetters.setBackground(new java.awt.Color(255, 255, 255));
        lblLetters.setForeground(new java.awt.Color(51, 51, 255));
        lblLetters.setText("Letters:");
        jPanel1.add(lblLetters);

        lblWords.setForeground(new java.awt.Color(51, 51, 255));
        lblWords.setText("Words:");
        jPanel1.add(lblWords);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        TextPaneEditor.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(TextPaneEditor);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TextPaneEditor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLetters;
    private javax.swing.JLabel lblLines;
    private javax.swing.JLabel lblWords;
    // End of variables declaration//GEN-END:variables
}
